<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="httptest" duration-ms="82" started-at="2021-11-04T05:04:02Z" finished-at="2021-11-04T05:04:02Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="82" started-at="2021-11-04T05:04:02Z" finished-at="2021-11-04T05:04:02Z">
      <class name="com.test.cases.Demo">
        <test-method status="PASS" signature="b()[pri:0, instance:com.test.cases.Demo@6f7fd0e6]" name="b" is-config="true" duration-ms="7" started-at="2021-11-04T13:04:02Z" finished-at="2021-11-04T13:04:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b -->
        <test-method status="PASS" signature="four()[pri:0, instance:com.test.cases.Demo@6f7fd0e6]" name="four" duration-ms="61" started-at="2021-11-04T13:04:02Z" finished-at="2021-11-04T13:04:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- four -->
        <test-method status="PASS" signature="one()[pri:0, instance:com.test.cases.Demo@6f7fd0e6]" name="one" duration-ms="1" started-at="2021-11-04T13:04:02Z" finished-at="2021-11-04T13:04:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- one -->
        <test-method status="FAIL" signature="three()[pri:0, instance:com.test.cases.Demo@6f7fd0e6]" name="three" duration-ms="2" started-at="2021-11-04T13:04:02Z" finished-at="2021-11-04T13:04:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at com.test.cases.Demo.three(Demo.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- three -->
        <test-method status="PASS" signature="two()[pri:0, instance:com.test.cases.Demo@6f7fd0e6]" name="two" duration-ms="0" started-at="2021-11-04T13:04:02Z" finished-at="2021-11-04T13:04:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- two -->
      </class> <!-- com.test.cases.Demo -->
    </test> <!-- Test -->
  </suite> <!-- httptest -->
</testng-results>
